apiVersion: batch/v1
kind: CronJob
metadata:
  name: kuma-sync-cronjob
  namespace: analytics
spec:
  # Roda a cada 6 horas (00:00, 06:00, 12:00, 18:00)
  schedule: "0 */6 * * *"
  concurrencyPolicy: Forbid 
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: kuma-sync-sa
          # Chave para baixar a imagem do repositório privado
          imagePullSecrets:
          - name: ghcr-secret
          # O pod usará uma ServiceAccount para se autenticar via Client Library
          containers:
          - name: sync-bot
            # Aqui entrará a URL da imagem no GitHub Packages (ghcr.io)
            image: ghcr.io/soureibr/health-observability:latest
            envFrom:
            - secretRef:
                name: kuma-creds
            env:
            - name: KUMA_URL
              value: "https://status.soureicdn.com"
            - name: DRY_RUN
              value: "false"
          restartPolicy: OnFailure